### ISSUE TITLE
CASTEP 9.0 available

### ISSUE THREAD

**Issue by mt1cmh** [rcgsheffield/iceberg_software#179]
Hi,

Asking on behalf of the Materials Science team, if we can have CASTEP 9.0 (it's labelled as 16.1 now for some reason?) installed on Iceberg, and for it to run along side 8.0 until we are happy that it is a stable version.

Thanks,

Chris

**Comment by mikecroucher** [comment]
Hi Chris

Done. Our website build system is having issues right now so I refer you to the source on github.
https://github.com/rcgsheffield/iceberg_software/blob/master/software/apps/CASTEP.rst

While performing testing, I discovered what appeared to be some misbehaving nodes. If a CASTEP 16.1 MPI test ended up on one of those nodes, it failed. On 'my' nodes (The ones paid for by one of the groups I collaborate with), all but one test passes and that test appears to be broken worldwide since it's missing a file.

I've reported it to Anthony.

Cheers,
Mike

**Comment by mikecroucher** [comment]
Installed

**Comment by mt1cmh** [comment]
Hi Mike,

That is great to know, I will pass that on the rest of our research group
here. From my own testing of using Iceberg, I think for students I have a
good feel for what sort of size jobs are feasible with the Iceberg queue
system (as much as it grinds my gears to see lots of single core jobs
running on Iceberg), so having CASTEP up to date and ready to run using a
modest number of processors (I think 16 became a magic number for me) will
be good (the jobs I have been needing to run on ARCHER are lots bigger and
need some 240 cores).

I will pass this all along to Colin and John.

Cheers,

Chris

On 9 February 2016 at 12:07, Mike Croucher <notifications@github.com> wrote:

> Hi Chris
>
> Done. Our website build system is having issues right now so I refer you
> to the source on github.
>
> https://github.com/rcgsheffield/iceberg_software/blob/master/software/apps/CASTEP.rst
>
> While performing testing, I discovered what appeared to be some
> misbehaving nodes. If a CASTEP 16.1 MPI test ended up on one of those
> nodes, it failed. On 'my' nodes (The ones paid for by one of the groups I
> collaborate with), all but one test passes and that test appears to be
> broken worldwide since it's missing a file.
>
> I've reported it to Anthony.
>
> Cheers,
> Mike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/179#issuecomment-181838727>
> .
>



-- 
Dr. Christopher Handley
Dept of Materials Science and Engineering
Sir Robert Hadfield Building
Mappin Street
Sheffield
S1 3JD
UK
