### ISSUE TITLE
Java 3D

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#279]
From the helpdesk:

Hi,

I’ve recently asked for ImageJ to be installed on Iceberg and I appreciate the speedy installation. However, when attempting to use some plugins the 3D java libraries are required to be installed. I have attempted an auto-installation but don’t have sufficient write privileges for the required installation folder. The ImageJ output from the auto-installation is as follows:

downloading http://132.187.25.13/java3d/j3d-1_5_2-linux-amd64.zip
to /tmp/j3d-1_5_2-linux-amd64.zip
create folder /tmp/java3d
Extracting j3d-jre.zip to /tmp/java3d
create folder /tmp/java3d/j3d-1_5_2-linux-amd64/
Extracting j3d-1_5_2-linux-amd64/j3d-jre.zip to /tmp/java3d
Extracting all to /usr/local/packages6/apps/binapps/java/jdk1.8.0_71/jre
No permissions to write to folder /usr/local/packages6/apps/binapps/java/jdk1.8.0_71/jre

Would it be possible to have these 3D java libraries installed?

Many Thanks,

Simon De-Ville

**Comment by mikecroucher** [comment]
I don't like how ImageJ wants to put Java3D in the system wide java path. It is probably more efficient, safe etc to have Java3D be a separate module install that hooks into whatever version of Java is in use.

I've asked Simon for an acceptance test for ImageJ.

**Comment by sde-ville** [comment]
Mike,

The only way I have found to discover if the 3D libraries are working is to open a file and use a 3D plugin.  have created a file and a IJ_Testing folder on fast data to check if all is working. To use the plugins I have found that I need to change the plugin directory for ImageJ and launch it from my X11 window via:

java -Xmx32G -Dplugins.dir=/mnt/fastdata/IJ_Testing/1.50g/plugins/ -jar $IMAGEJ_DIR//ij.jar

Once ImageJ has launched open the test file /mnt/fastdata/IJ_Testing/MikeTest.tif this will be a 10 slice 3D tif file.Then navigate to Plugins>3D>3D Viewer, this is the point at which the previous prompt to auto-install would appear. If all is well a 3D Viewer window should open displaying the 3D tif file. Additionally to check that processing plugins function you can also try Plugins>BoneJ>Skeletonise 3D, this operation may take a minute to complete if functioning otherwise you will again be prompted to install the 3D java libraries. 

If you've any further questions just let me know.

**Comment by mikecroucher** [comment]
I tried a separate install of Java 3D and did all of the CLASSPATH, LD_LIBRARY_PATH etc work as described in http://download.java.net/media/java3d/builds/release/1.5.2/README-download.html. 

ImageJ's 3D plugin refused to see it. It seems that we have no choice but to include it in the jre.
I did this with the relevant permissions and it seems to work.

I've also updated the documentation at http://docs.iceberg.shef.ac.uk/en/latest/software/apps/imagej.html to reflect the required changes and also to include how to use the system plugins folder.

Could you give it a spin and let me know how you get on please?
